# -*- coding: utf-8 -*-
"""ML_Airbnb_Crime_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sg64UiKlLeefODy7Au9N0xgoduA8Ejb1

# 🤖 Machine Learning Analysis: Predicting Airbnb Prices from Crime Rates
This notebook applies regression models to predict Airbnb prices using crime data (Robbery and Assault per 100k residents).
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

sns.set(style='whitegrid')

"""## 📥 Load Dataset"""

# Load the merged dataset
merged_data = pd.read_csv('/mnt/data/merged_crime_airbnb_data.csv')
merged_data.head()

"""## 🎯 Features and Target
- **Features**: Robbery and Assault rates per 100k people
- **Target**: Average Airbnb price in each state
"""

# Feature selection
X = merged_data[['Robbery_per_100k', 'Assault_per_100k']]
y = merged_data['Average_Price']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""## 🔹 Linear Regression"""

lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)
print(f"R² Score: {r2_score(y_test, y_pred_lr):.2f}")
print(f"MSE: {mean_squared_error(y_test, y_pred_lr):.2f}")

"""## 🔸 Random Forest Regressor"""

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)
print(f"R² Score: {r2_score(y_test, y_pred_rf):.2f}")
print(f"MSE: {mean_squared_error(y_test, y_pred_rf):.2f}")

"""## 📌 Feature Importance (Random Forest)"""

feat_importances = pd.Series(rf.feature_importances_, index=X.columns)
feat_importances.sort_values().plot(kind='barh', title='Feature Importances')
plt.xlabel('Importance')
plt.show()

"""## 🧠 What Does Feature Importance Mean?

The bar chart above shows how much each input variable (feature) contributes to predicting the average Airbnb price, according to the Random Forest model.

- **Higher values** indicate features that the model relied on more heavily to make decisions.
- **Lower values** suggest less influence on the final prediction.

For example:
- If `Assault_per_100k` has higher importance than `Robbery_per_100k`, it means that Airbnb prices tend to vary more consistently with assault rates than robbery rates — at least according to the model.

🔍 **Note**: These importances are based on how much each feature reduces prediction error across all decision trees in the forest.

"""